cache: pip

matrix:
  include:
    - language: python
      python: "2.7"
      env: TOXENV=py27

    - language: python
      python: "3.4"
      env: TOXENV=py34

    - language: python
      python: "3.5"
      env: TOXENV=py35

    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.7"
      env: TOXENV=py37

    - language: python
      python: "3.8"
      env: TOXENV=py38

    - language: python
      python: "3.4"
      env: TOXENV=pep8

install:
    - pip install tox
    - if [ "$TOXENV" = 'py38' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py38' ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: "BKWCxvfr5PDd2pLsbRVkyLu8/bV2EzsYqISfFQZml84NCpXmPMah2NAjeIS5OXIJmKxHDzvzgfHGAWFT/H/COE1UbnEjp9oGhN3BNThjH7anaMHSr27T4beDntnbsO+boWAdUORzy1QU/DDvqhhXTXybhywENYRuTXIMB7D4PSc="
    on:
        tags: true
        condition: $TOXENV = py38
